openapi: 3.0.0
info:
  title: VelHerd - API documentation
  version: 1.0.0
  description: You can use VelHerd API if you have account on VelHerd web site.
servers:
  - url: '{{baseUrl}}'
paths:
  /api/access_tokens:
    post:
      summary: JWToken
      tags:
        - Reference
        - Authorization
      responses: {}
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                integration_token:
                  type: object
                  properties:
                    token:
                      type: string
  /api/{apiVersion}/base_units:
    get:
      summary: get_base_units
      tags:
        - API endpoints
        - Base Units
      responses: {}
      description: >-
        ## API Endpoint: Get Farm Units


        ### Purpose


        This endpoint retrieves a list of farm units from the server. It is
        useful for clients that need to display or process information related
        to various farm units available in the system.


        ### Request Format


        - **Method**: GET
            
        - **URL**: {{baseUrl}}/api/{{apiVersion}}/farm_units
            

        ### Response Structure


        The response will contain a JSON object with the following structure:


        - **status**: Indicates the success or failure of the request (e.g.,
        "success" or "error").
            
        - **data**: An array of farm unit objects, where each object contains:
            
            - **id**: Unique identifier for the farm unit.
                
            - **name**: Name of the farm unit.
                
            - **description**: Description for the farm unit.
                
            - **external_id**: External ID for the farm unit.
                
            - **active**: Active status. Can be `true` or `false`
                
            - **created_at**: Created time
                
            - **updated_at**: Updated time
                

        ### Example Response


        ``` json

        {
            "data": [
                {
                    "id": "1",
                    "type": "farm_unit",
                    "attributes": {
                        "id": 1,
                        "name": "Farm Unit A",
                        "description": null,
                        "external_id": null,
                        "active": false,
                        "created_at": "2025-06-12T11:43:22.597+03:00",
                        "updated_at": "2025-06-12T11:43:22.597+03:00"
                    }
                },
                {
                    "id": "2",
                    "type": "farm_unit",
                    "attributes": {
                        "id": 2,
                        "name": "Farm Unit B",
                        "description": "Some Description",
                        "external_id": 123,
                        "active": true,
                        "created_at": "2025-06-12T12:08:15.653+03:00",
                        "updated_at": "2025-06-12T14:17:34.497+03:00"
                    }
                }
            ]
        }

         ```

        This response provides a structured overview of the farm units, enabling
        clients to easily access and utilize the information.
    parameters:
      - name: apiVersion
        in: path
        required: true
        schema:
          type: string
  /api/{apiVersion}/base_units/ids:
    get:
      summary: get_base_unit_ids
      tags:
        - API endpoints
        - Base Units
      responses: {}
    parameters:
      - name: apiVersion
        in: path
        required: true
        schema:
          type: string
  /api/{apiVersion}/base_units/1:
    get:
      summary: get_base_unit
      tags:
        - API endpoints
        - Base Units
      responses: {}
    parameters:
      - name: apiVersion
        in: path
        required: true
        schema:
          type: string
  /api/{apiVersion}/farm_units:
    get:
      summary: get_farm_units
      tags:
        - API endpoints
        - Farm Units
      responses: {}
      description: >-
        ## API Endpoint: Get Farm Units


        ### Purpose


        This endpoint retrieves a list of farm units from the server. It is
        useful for clients that need to display or process information related
        to various farm units available in the system.


        ### Request Format


        - **Method**: GET
            
        - **URL**: {{baseUrl}}/api/{{apiVersion}}/farm_units
            

        ### Response Structure


        The response will contain a JSON object with the following structure:


        - **status**: Indicates the success or failure of the request (e.g.,
        "success" or "error").
            
        - **data**: An array of farm unit objects, where each object contains:
            
            - **id**: Unique identifier for the farm unit.
                
            - **name**: Name of the farm unit.
                
            - **description**: Description for the farm unit.
                
            - **external_id**: External ID for the farm unit.
                
            - **active**: Active status. Can be `true` or `false`
                
            - **created_at**: Created time
                
            - **updated_at**: Updated time
                

        ### Example Response


        ``` json

        {
            "data": [
                {
                    "id": "1",
                    "type": "farm_unit",
                    "attributes": {
                        "id": 1,
                        "name": "Farm Unit A",
                        "description": null,
                        "external_id": null,
                        "active": false,
                        "created_at": "2025-06-12T11:43:22.597+03:00",
                        "updated_at": "2025-06-12T11:43:22.597+03:00"
                    }
                },
                {
                    "id": "2",
                    "type": "farm_unit",
                    "attributes": {
                        "id": 2,
                        "name": "Farm Unit B",
                        "description": "Some Description",
                        "external_id": 123,
                        "active": true,
                        "created_at": "2025-06-12T12:08:15.653+03:00",
                        "updated_at": "2025-06-12T14:17:34.497+03:00"
                    }
                }
            ]
        }

         ```

        This response provides a structured overview of the farm units, enabling
        clients to easily access and utilize the information.
    parameters:
      - name: apiVersion
        in: path
        required: true
        schema:
          type: string
    post:
      summary: create_farm_unit
      tags:
        - API endpoints
        - Farm Units
      responses: {}
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                data:
                  type: object
                  properties:
                    name:
                      type: string
                    description:
                      type: string
                    external_id:
                      type: integer
                    active:
                      type: boolean
  /api/{apiVersion}/farm_units/ids:
    get:
      summary: get_farm_unit_ids
      tags:
        - API endpoints
        - Farm Units
      responses: {}
    parameters:
      - name: apiVersion
        in: path
        required: true
        schema:
          type: string
  /api/{apiVersion}/farm_units/1:
    get:
      summary: get_farm_unit
      tags:
        - API endpoints
        - Farm Units
      responses: {}
    parameters:
      - name: apiVersion
        in: path
        required: true
        schema:
          type: string
  /api/{apiVersion}/farm_units/2:
    put:
      summary: update_farm_unit
      tags:
        - API endpoints
        - Farm Units
      responses: {}
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                data:
                  type: object
                  properties:
                    description:
                      type: string
    parameters:
      - name: apiVersion
        in: path
        required: true
        schema:
          type: string
  /api/{apiVersion}/farm_units/3:
    delete:
      summary: destroy_farm_unit
      tags:
        - API endpoints
        - Farm Units
      responses: {}
    parameters:
      - name: apiVersion
        in: path
        required: true
        schema:
          type: string
  /api/{apiVersion}/units:
    get:
      summary: get_units
      tags:
        - API endpoints
        - Units
      responses: {}
      description: >-
        ## API Endpoint: Get Farm Units


        ### Purpose


        This endpoint retrieves a list of farm units from the server. It is
        useful for clients that need to display or process information related
        to various farm units available in the system.


        ### Request Format


        - **Method**: GET
            
        - **URL**: {{baseUrl}}/api/{{apiVersion}}/farm_units
            

        ### Response Structure


        The response will contain a JSON object with the following structure:


        - **status**: Indicates the success or failure of the request (e.g.,
        "success" or "error").
            
        - **data**: An array of farm unit objects, where each object contains:
            
            - **id**: Unique identifier for the farm unit.
                
            - **name**: Name of the farm unit.
                
            - **description**: Description for the farm unit.
                
            - **external_id**: External ID for the farm unit.
                
            - **active**: Active status. Can be `true` or `false`
                
            - **created_at**: Created time
                
            - **updated_at**: Updated time
                

        ### Example Response


        ``` json

        {
            "data": [
                {
                    "id": "1",
                    "type": "farm_unit",
                    "attributes": {
                        "id": 1,
                        "name": "Farm Unit A",
                        "description": null,
                        "external_id": null,
                        "active": false,
                        "created_at": "2025-06-12T11:43:22.597+03:00",
                        "updated_at": "2025-06-12T11:43:22.597+03:00"
                    }
                },
                {
                    "id": "2",
                    "type": "farm_unit",
                    "attributes": {
                        "id": 2,
                        "name": "Farm Unit B",
                        "description": "Some Description",
                        "external_id": 123,
                        "active": true,
                        "created_at": "2025-06-12T12:08:15.653+03:00",
                        "updated_at": "2025-06-12T14:17:34.497+03:00"
                    }
                }
            ]
        }

         ```

        This response provides a structured overview of the farm units, enabling
        clients to easily access and utilize the information.
    parameters:
      - name: apiVersion
        in: path
        required: true
        schema:
          type: string
    post:
      summary: create_unit
      tags:
        - API endpoints
        - Units
      responses: {}
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                data:
                  type: object
                  properties:
                    name:
                      type: string
                    description:
                      type: string
                    external_id:
                      type: integer
                    active:
                      type: boolean
  /api/{apiVersion}/units/ids:
    get:
      summary: get_unit_ids
      tags:
        - API endpoints
        - Units
      responses: {}
    parameters:
      - name: apiVersion
        in: path
        required: true
        schema:
          type: string
  /api/{apiVersion}/units/1:
    get:
      summary: get_unit
      tags:
        - API endpoints
        - Units
      responses: {}
    parameters:
      - name: apiVersion
        in: path
        required: true
        schema:
          type: string
    put:
      summary: update_unit
      tags:
        - API endpoints
        - Units
      responses: {}
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                data:
                  type: object
                  properties:
                    description:
                      type: string
  /api/{apiVersion}/units/3:
    delete:
      summary: destroy_unit
      tags:
        - API endpoints
        - Units
      responses: {}
    parameters:
      - name: apiVersion
        in: path
        required: true
        schema:
          type: string
