name: Deploy API docs

on:
  push:
    branches: [ main ]
    paths:
      - "velherd_openapi.yaml"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Redoc CLI
        run: npm install -g redoc-cli

      - name: Generate HTML docs
        run: |
          mkdir -p docs
          redoc-cli bundle velherd_openapi.yaml -o docs/index.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
