name: Deploy API docs

on:
  push:
    branches: [ main ]
    paths: [ "velherd_openapi.yaml" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with: { node-version: 18 }
      - run: |
          npm install -g redoc-cli
          mkdir -p docs
          redoc-cli bundle velherd_openapi.yaml -o docs/index.html
          touch docs/.nojekyll
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          publish_branch: gh-pages
          force_orphan: true
